version: "3.7"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
      - elasticsearch
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  sidekiq:
    build: .
    command: bash -c "bundle exec sidekiq -C config/sidekiq.yml"
    links:
      - redis
    volumes:
      - .:/app
